[env:controller]
platform  = espressif32
board     = adafruit_feather_esp32s3_reversetft
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DPREFER_SDFAT_LIBRARY

lib_deps =
    adafruit/Adafruit VS1053 Library
    adafruit/SdFat - Adafruit Fork
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ST7735 and ST7789 Library
